### ISSUE TITLE
Create logfile per hour and store this on USB drive

### ISSUE THREAD

**Issue by jacob-kamminga** [Ecomoni/nestbox-raspberrypi#56]
This way we can check that server.py syncs this with MDS.

**Comment by Jessseee** [comment]
The simplest solution for this is a cronjob `0 * * * * tail -n 50 /var/log/record_entries.log > /media/nestbox/<usb-drive>/entries/$(date +\%Y-\%m-\%d_\%H-\%M-\%S_\%6N).log`
